/**
 * @module PeriodicTable
 * @description Raw Geant4 element data for Z = 1 (Hydrogen) through Z = 98 (Californium).
 *
 * Each entry contains:
 *   - atomicNumber — Atomic number (Z)
 *   - symbol       — Chemical symbol
 *   - elementType  — Geant4 identifier (e.g. 'G4_Fe')
 *   - density      — g/cm³
 *   - energy       — Mean excitation energy in eV
 *
 * This module provides raw data only. For lookups and the centralized
 * registry, use MaterialDatabase.js.
 *
 * @see MaterialDatabase.js  — centralized material registry consuming this data.
 * @see CompoundMaterials.js — compound material data.
 */

const elements = [
  {
    atomicNumber: 1,
    symbol: 'H',
    elementType: 'G4_H',
    density: 8.3748e-5,
    energy: 19.2,
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    elementType: 'G4_He',
    density: 0.000166322,
    energy: 41.8,
  },
  {
    atomicNumber: 3,
    symbol: 'Li',
    elementType: 'G4_Li',
    density: 0.534,
    energy: 40,
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    elementType: 'G4_Be',
    density: 1.848,
    energy: 63.7,
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    elementType: 'G4_B',
    density: 2.37,
    energy: 76,
  },
  { atomicNumber: 6, symbol: 'C', elementType: 'G4_C', density: 2, energy: 81 },
  {
    atomicNumber: 7,
    symbol: 'N',
    elementType: 'G4_N',
    density: 0.0011652,
    energy: 82,
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    elementType: 'G4_O',
    density: 0.00133151,
    energy: 95,
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    elementType: 'G4_F',
    density: 0.00158029,
    energy: 115,
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    elementType: 'G4_Ne',
    density: 0.000838505,
    energy: 137,
  },
  {
    atomicNumber: 11,
    symbol: 'Na',
    elementType: 'G4_Na',
    density: 0.971,
    energy: 149,
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    elementType: 'G4_Mg',
    density: 1.74,
    energy: 156,
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    elementType: 'G4_Al',
    density: 2.699,
    energy: 166,
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    elementType: 'G4_Si',
    density: 2.33,
    energy: 173,
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    elementType: 'G4_P',
    density: 2.2,
    energy: 173,
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    elementType: 'G4_S',
    density: 2,
    energy: 180,
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    elementType: 'G4_Cl',
    density: 0.00299473,
    energy: 174,
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    elementType: 'G4_Ar',
    density: 0.00166201,
    energy: 188,
  },
  {
    atomicNumber: 19,
    symbol: 'K',
    elementType: 'G4_K',
    density: 0.862,
    energy: 190,
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    elementType: 'G4_Ca',
    density: 1.55,
    energy: 191,
  },
  {
    atomicNumber: 21,
    symbol: 'Sc',
    elementType: 'G4_Sc',
    density: 2.989,
    energy: 216,
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    elementType: 'G4_Ti',
    density: 4.54,
    energy: 233,
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    elementType: 'G4_V',
    density: 6.11,
    energy: 245,
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    elementType: 'G4_Cr',
    density: 7.18,
    energy: 257,
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    elementType: 'G4_Mn',
    density: 7.44,
    energy: 272,
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    elementType: 'G4_Fe',
    density: 7.874,
    energy: 286,
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    elementType: 'G4_Co',
    density: 8.9,
    energy: 297,
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    elementType: 'G4_Ni',
    density: 8.902,
    energy: 311,
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    elementType: 'G4_Cu',
    density: 8.96,
    energy: 322,
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    elementType: 'G4_Zn',
    density: 7.133,
    energy: 330,
  },
  {
    atomicNumber: 31,
    symbol: 'Ga',
    elementType: 'G4_Ga',
    density: 5.904,
    energy: 334,
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    elementType: 'G4_Ge',
    density: 5.323,
    energy: 350,
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    elementType: 'G4_As',
    density: 5.73,
    energy: 347,
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    elementType: 'G4_Se',
    density: 4.5,
    energy: 348,
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    elementType: 'G4_Br',
    density: 0.0070721,
    energy: 343,
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    elementType: 'G4_Kr',
    density: 0.00347832,
    energy: 352,
  },
  {
    atomicNumber: 37,
    symbol: 'Rb',
    elementType: 'G4_Rb',
    density: 1.532,
    energy: 363,
  },
  {
    atomicNumber: 38,
    symbol: 'Sr',
    elementType: 'G4_Sr',
    density: 2.54,
    energy: 366,
  },
  {
    atomicNumber: 39,
    symbol: 'Y',
    elementType: 'G4_Y',
    density: 4.469,
    energy: 379,
  },
  {
    atomicNumber: 40,
    symbol: 'Zr',
    elementType: 'G4_Zr',
    density: 6.506,
    energy: 393,
  },
  {
    atomicNumber: 41,
    symbol: 'Nb',
    elementType: 'G4_Nb',
    density: 8.57,
    energy: 417,
  },
  {
    atomicNumber: 42,
    symbol: 'Mo',
    elementType: 'G4_Mo',
    density: 10.22,
    energy: 424,
  },
  {
    atomicNumber: 43,
    symbol: 'Tc',
    elementType: 'G4_Tc',
    density: 11.5,
    energy: 428,
  },
  {
    atomicNumber: 44,
    symbol: 'Ru',
    elementType: 'G4_Ru',
    density: 12.41,
    energy: 441,
  },
  {
    atomicNumber: 45,
    symbol: 'Rh',
    elementType: 'G4_Rh',
    density: 12.41,
    energy: 449,
  },
  {
    atomicNumber: 46,
    symbol: 'Pd',
    elementType: 'G4_Pd',
    density: 12.02,
    energy: 470,
  },
  {
    atomicNumber: 47,
    symbol: 'Ag',
    elementType: 'G4_Ag',
    density: 10.5,
    energy: 470,
  },
  {
    atomicNumber: 48,
    symbol: 'Cd',
    elementType: 'G4_Cd',
    density: 8.65,
    energy: 469,
  },
  {
    atomicNumber: 49,
    symbol: 'In',
    elementType: 'G4_In',
    density: 7.31,
    energy: 488,
  },
  {
    atomicNumber: 50,
    symbol: 'Sn',
    elementType: 'G4_Sn',
    density: 7.31,
    energy: 488,
  },
  {
    atomicNumber: 51,
    symbol: 'Sb',
    elementType: 'G4_Sb',
    density: 6.691,
    energy: 487,
  },
  {
    atomicNumber: 52,
    symbol: 'Te',
    elementType: 'G4_Te',
    density: 6.24,
    energy: 485,
  },
  {
    atomicNumber: 53,
    symbol: 'I',
    elementType: 'G4_I',
    density: 4.93,
    energy: 491,
  },
  {
    atomicNumber: 54,
    symbol: 'Xe',
    elementType: 'G4_Xe',
    density: 0.00548536,
    energy: 482,
  },
  {
    atomicNumber: 55,
    symbol: 'Cs',
    elementType: 'G4_Cs',
    density: 1.873,
    energy: 488,
  },
  {
    atomicNumber: 56,
    symbol: 'Ba',
    elementType: 'G4_Ba',
    density: 3.5,
    energy: 491,
  },
  {
    atomicNumber: 57,
    symbol: 'La',
    elementType: 'G4_La',
    density: 6.154,
    energy: 501,
  },
  {
    atomicNumber: 58,
    symbol: 'Ce',
    elementType: 'G4_Ce',
    density: 6.657,
    energy: 523,
  },
  {
    atomicNumber: 59,
    symbol: 'Pr',
    elementType: 'G4_Pr',
    density: 6.71,
    energy: 535,
  },
  {
    atomicNumber: 60,
    symbol: 'Nd',
    elementType: 'G4_Nd',
    density: 6.9,
    energy: 546,
  },
  {
    atomicNumber: 61,
    symbol: 'Pm',
    elementType: 'G4_Pm',
    density: 7.22,
    energy: 560,
  },
  {
    atomicNumber: 62,
    symbol: 'Sm',
    elementType: 'G4_Sm',
    density: 7.46,
    energy: 574,
  },
  {
    atomicNumber: 63,
    symbol: 'Eu',
    elementType: 'G4_Eu',
    density: 5.243,
    energy: 580,
  },
  {
    atomicNumber: 64,
    symbol: 'Gd',
    elementType: 'G4_Gd',
    density: 7.9004,
    energy: 591,
  },
  {
    atomicNumber: 65,
    symbol: 'Tb',
    elementType: 'G4_Tb',
    density: 8.229,
    energy: 614,
  },
  {
    atomicNumber: 66,
    symbol: 'Dy',
    elementType: 'G4_Dy',
    density: 8.55,
    energy: 628,
  },
  {
    atomicNumber: 67,
    symbol: 'Ho',
    elementType: 'G4_Ho',
    density: 8.795,
    energy: 650,
  },
  {
    atomicNumber: 68,
    symbol: 'Er',
    elementType: 'G4_Er',
    density: 9.066,
    energy: 658,
  },
  {
    atomicNumber: 69,
    symbol: 'Tm',
    elementType: 'G4_Tm',
    density: 9.321,
    energy: 674,
  },
  {
    atomicNumber: 70,
    symbol: 'Yb',
    elementType: 'G4_Yb',
    density: 6.73,
    energy: 684,
  },
  {
    atomicNumber: 71,
    symbol: 'Lu',
    elementType: 'G4_Lu',
    density: 9.84,
    energy: 694,
  },
  {
    atomicNumber: 72,
    symbol: 'Hf',
    elementType: 'G4_Hf',
    density: 13.31,
    energy: 705,
  },
  {
    atomicNumber: 73,
    symbol: 'Ta',
    elementType: 'G4_Ta',
    density: 16.654,
    energy: 718,
  },
  {
    atomicNumber: 74,
    symbol: 'W',
    elementType: 'G4_W',
    density: 19.3,
    energy: 727,
  },
  {
    atomicNumber: 75,
    symbol: 'Re',
    elementType: 'G4_Re',
    density: 21.02,
    energy: 736,
  },
  {
    atomicNumber: 76,
    symbol: 'Os',
    elementType: 'G4_Os',
    density: 22.57,
    energy: 746,
  },
  {
    atomicNumber: 77,
    symbol: 'Ir',
    elementType: 'G4_Ir',
    density: 22.42,
    energy: 757,
  },
  {
    atomicNumber: 78,
    symbol: 'Pt',
    elementType: 'G4_Pt',
    density: 21.45,
    energy: 790,
  },
  {
    atomicNumber: 79,
    symbol: 'Au',
    elementType: 'G4_Au',
    density: 19.32,
    energy: 790,
  },
  {
    atomicNumber: 80,
    symbol: 'Hg',
    elementType: 'G4_Hg',
    density: 13.546,
    energy: 800,
  },
  {
    atomicNumber: 81,
    symbol: 'Tl',
    elementType: 'G4_Tl',
    density: 11.72,
    energy: 810,
  },
  {
    atomicNumber: 82,
    symbol: 'Pb',
    elementType: 'G4_Pb',
    density: 11.35,
    energy: 823,
  },
  {
    atomicNumber: 83,
    symbol: 'Bi',
    elementType: 'G4_Bi',
    density: 9.747,
    energy: 823,
  },
  {
    atomicNumber: 84,
    symbol: 'Po',
    elementType: 'G4_Po',
    density: 9.32,
    energy: 830,
  },
  {
    atomicNumber: 85,
    symbol: 'At',
    elementType: 'G4_At',
    density: 9.32,
    energy: 825,
  },
  {
    atomicNumber: 86,
    symbol: 'Rn',
    elementType: 'G4_Rn',
    density: 0.00900662,
    energy: 794,
  },
  {
    atomicNumber: 87,
    symbol: 'Fr',
    elementType: 'G4_Fr',
    density: 1,
    energy: 827,
  },
  {
    atomicNumber: 88,
    symbol: 'Ra',
    elementType: 'G4_Ra',
    density: 5,
    energy: 826,
  },
  {
    atomicNumber: 89,
    symbol: 'Ac',
    elementType: 'G4_Ac',
    density: 10.07,
    energy: 841,
  },
  {
    atomicNumber: 90,
    symbol: 'Th',
    elementType: 'G4_Th',
    density: 11.72,
    energy: 847,
  },
  {
    atomicNumber: 91,
    symbol: 'Pa',
    elementType: 'G4_Pa',
    density: 15.37,
    energy: 878,
  },
  {
    atomicNumber: 92,
    symbol: 'U',
    elementType: 'G4_U',
    density: 18.95,
    energy: 890,
  },
  {
    atomicNumber: 93,
    symbol: 'Np',
    elementType: 'G4_Np',
    density: 20.25,
    energy: 902,
  },
  {
    atomicNumber: 94,
    symbol: 'Pu',
    elementType: 'G4_Pu',
    density: 19.84,
    energy: 921,
  },
  {
    atomicNumber: 95,
    symbol: 'Am',
    elementType: 'G4_Am',
    density: 13.67,
    energy: 934,
  },
  {
    atomicNumber: 96,
    symbol: 'Cm',
    elementType: 'G4_Cm',
    density: 13.51,
    energy: 939,
  },
  {
    atomicNumber: 97,
    symbol: 'Bk',
    elementType: 'G4_Bk',
    density: 14,
    energy: 952,
  },
  {
    atomicNumber: 98,
    symbol: 'Cf',
    elementType: 'G4_Cf',
    density: 10,
    energy: 966,
  },
];

export { elements };
